### ISSUE TITLE
Add additional fields per input

### ISSUE THREAD

**Issue by mpucholblasco** [mpucholblasco/s3logsbeat#5]
In config yaml, add additional fields per input.

For instance:
```yaml
s3logsbeat:
  inputs:
    - type: sqs
      queues_url:
        - https://sqs.us-east-2.amazonaws.com/123456789012/MyQueueForCloudFront
      log_format: cloudfront
      poll_frequency: 1m
      # Optional additional fields
      fields:
        environment: staging
```
